#!/usr/bin/env bash
# Regenerates src/constants.hpp: pi, 2/pi, ln 2, ln 10 and e with 3584 fraction
# bits (896 hex digits), truncated. Requires bc.
set -euo pipefail

digits=896
out="$(dirname "$0")/../src/constants.hpp"

hex() {  # $1: bc expression -> integer part and the first $digits fraction hex digits
    local v int frac
    v=$(echo "obase=16; scale=1200; $1" | BC_LINE_LENGTH=0 bc -l)
    int=${v%%.*}
    frac=${v#*.}
    printf '%s%s' "$int" "${frac:0:$digits}"
}

emit() {  # $1: C++ name, $2: bc expression
    printf 'inline constexpr const char* %s =\n' "$1"
    hex "$2" | fold -w 64 | sed 's/.*/    "&"/'
    printf ';\n\n'
}

{
    printf '#pragma once\n\n'
    printf '// Generated by tools/constants.sh with bc; do not edit.\n'
    printf '// Each value is (hex digits as an integer) * 2^-constantFractionBits, truncated.\n\n'
    printf 'namespace calculate_core::detail {\n\n'
    printf 'inline constexpr int constantFractionBits = %d;\n\n' $((digits * 4))
    emit piHex '4*a(1)'
    emit twoOverPiHex '2/(4*a(1))'
    emit ln2Hex 'l(2)'
    emit ln10Hex 'l(10)'
    emit eHex 'e(1)'
    printf '}  // namespace calculate_core::detail\n'
} > "$out"
