#!/usr/bin/env python3
"""Writes src/physical_constants.hpp from tools/codata-2022.txt (the CODATA 2022 table exactly as NIST
publishes it, https://physics.nist.gov/cuu/Constants/Table/allascii.txt) and tools/physical-constants.tsv
(our names). With --check it only compares, and fails when the header is out of date."""
import os
import sys

here = os.path.dirname(os.path.abspath(__file__))
header = os.path.join(here, '..', 'src', 'physical_constants.hpp')


def read_codata(path):
    """quantity -> (value, uncertainty, unit), with the spaces removed from the numbers."""
    lines = open(path, encoding='utf-8').read().split('\n')
    start = next(i for i, line in enumerate(lines) if line.startswith('-----')) + 1
    table = {}
    for line in lines[start:]:
        if line.strip():
            table[line[:60].strip()] = (line[60:85].replace(' ', ''), line[85:110].replace(' ', ''), line[110:].strip())
    return table


def literal(text):
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"') + '"'


def generate():
    codata = read_codata(os.path.join(here, 'codata-2022.txt'))
    rows, names = [], set()
    for line in open(os.path.join(here, 'physical-constants.tsv'), encoding='utf-8'):
        if line.startswith('#') or not line.strip():
            continue
        name, quantity, definition = (line.rstrip('\n').split('\t') + [''])[:3]
        if quantity not in codata:
            sys.exit(f'{name}: no quantity "{quantity}" in codata-2022.txt')
        if name in names:
            sys.exit(f'{name}: used twice')
        names.add(name)
        value, uncertainty, unit = codata[quantity]
        exact = uncertainty == '(exact)'
        if ('...' in value) != (definition != ''):
            sys.exit(f'{name}: a definition is needed exactly when NIST cuts the value short ("...")')
        if not definition:
            definition = value if exact else value + '+/-' + uncertainty
        rows.append(f'    {{{literal(name)}, {literal(quantity)}, {literal(definition)}, {literal(value)}, '
                    f'{literal(unit)}, {"true" if exact else "false"}}},')
    return '\n'.join([
        '#pragma once',
        '',
        '// Generated by tools/physical_constants.py from tools/codata-2022.txt (CODATA 2022, published by',
        '// NIST) and tools/physical-constants.tsv; do not edit.',
        '',
        '#include <array>',
        '#include <string_view>',
        '',
        'namespace calculate_core::detail {',
        '',
        'struct PhysicalConstant {',
        '    std::string_view name;        // as typed: "G"',
        '    std::string_view quantity;    // CODATA\'s name: "Newtonian constant of gravitation"',
        '    std::string_view definition;  // what the name stands for: "6.67430e-11+/-0.00015e-11", "h/(2*pi)"',
        '    std::string_view nistValue;   // the value as NIST prints it, spaces removed: "1.054571817...e-34"',
        '    std::string_view unit;        // SI, as NIST writes it: "m^3 kg^-1 s^-2"; empty for pure numbers',
        '    bool exact;                   // exact by the definition of the SI',
        '};',
        '',
        f'inline constexpr std::array<PhysicalConstant, {len(rows)}> physicalConstants{{{{',
        *rows,
        '}};',
        '',
        '}  // namespace calculate_core::detail',
        '',
    ])


def main():
    text = generate()
    if '--check' in sys.argv[1:]:
        current = open(header, encoding='utf-8').read() if os.path.exists(header) else ''
        sys.exit(0 if current == text else 'src/physical_constants.hpp is out of date: run tools/physical_constants.py')
    with open(header, 'w', encoding='utf-8') as out:
        out.write(text)


main()
