#include "catalogue.hpp"

namespace calculate_core::detail {

namespace {

const std::vector<FunctionText>& table() {
    static const std::vector<FunctionText> rows{
        {"pi", "Pi", "The ratio of a circle's circumference to its diameter.",
         "pi", "Constants", {}},
        {"e", "Euler's number", "The base of the natural logarithm.",
         "e", "Constants", {}},
        {"tau", "Tau", "Twice pi: the ratio of a circle's circumference to its radius.",
         "tau", "Constants", {}},
        {"sqrt2", "Square root of 2", "The positive number whose square is 2.",
         "sqrt2", "Constants", {}},
        {"phi", "Golden ratio", "(1 + √5)/2, the positive root of x² = x + 1.",
         "phi", "Constants", {}},
        {"egamma", "Euler–Mascheroni constant", "The limit of 1 + 1/2 + … + 1/n − ln n.",
         "egamma", "Constants", {}},
        {"catalan", "Catalan's constant", "1 − 1/3² + 1/5² − 1/7² + …, over the odd squares with alternating signs.",
         "catalan", "Constants", {}},
        {"apery", "Apéry's constant", "1 + 1/2³ + 1/3³ + …, the value of zeta(3).",
         "apery", "Constants", {}},
        {"plastic", "Plastic ratio", "The real root of x³ = x + 1.",
         "plastic", "Constants", {}},
        {"omega", "Omega constant", "The number x with x·eˣ = 1.",
         "omega", "Constants", {}},
        {"sqrt", "Square root", "The non-negative number whose square is x.",
         "sqrt(2)", "Powers and roots", {{"x", ArgumentKind::Number}}},
        {"cbrt", "Cube root", "The real number whose cube is x.",
         "cbrt(27)", "Powers and roots", {{"x", ArgumentKind::Number}}},
        {"root", "n-th root", "The real number whose n-th power is x.",
         "root(32, 5)", "Powers and roots", {{"x", ArgumentKind::Number}, {"n", ArgumentKind::Number}}},
        {"exp", "Exponential", "e raised to the power x.",
         "exp(1)", "Powers and roots", {{"x", ArgumentKind::Number}}},
        {"exp2", "Power of two", "2 raised to the power x.",
         "exp2(10)", "Powers and roots", {{"x", ArgumentKind::Number}}},
        {"exp10", "Power of ten", "10 raised to the power x.",
         "exp10(3)", "Powers and roots", {{"x", ArgumentKind::Number}}},
        {"sq", "Square", "x times x.",
         "sq(12)", "Powers and roots", {{"x", ArgumentKind::Number}}},
        {"sqrtpi", "Square root of x·π", "The square root of x times pi.",
         "sqrtpi(2)", "Powers and roots", {{"x", ArgumentKind::Number}}},
        {"hypot", "Hypotenuse", "The square root of x² + y², without overflow.",
         "hypot(3, 4)", "Powers and roots", {{"x", ArgumentKind::Number}, {"y", ArgumentKind::Number}}},
        {"ln", "Natural logarithm", "The power to which e must be raised to give x.",
         "ln(2)", "Logarithms", {{"x", ArgumentKind::Number}}},
        {"log", "Logarithm", "The logarithm of x in base 10 (or e, when the setting says so), or in the given base.",
         "log(1000)", "Logarithms", {{"x", ArgumentKind::Number}, {"base", ArgumentKind::Number}}},
        {"log2", "Binary logarithm", "The power to which 2 must be raised to give x.",
         "log2(8)", "Logarithms", {{"x", ArgumentKind::Number}}},
        {"sin", "Sine", "The sine of the angle x.",
         "sin(1)", "Trigonometry", {{"x", ArgumentKind::Angle}}},
        {"cos", "Cosine", "The cosine of the angle x.",
         "cos(1)", "Trigonometry", {{"x", ArgumentKind::Angle}}},
        {"tan", "Tangent", "The tangent of the angle x.",
         "tan(1)", "Trigonometry", {{"x", ArgumentKind::Angle}}},
        {"sec", "Secant", "One over the cosine of the angle x.",
         "sec(1)", "Trigonometry", {{"x", ArgumentKind::Angle}}},
        {"csc", "Cosecant", "One over the sine of the angle x.",
         "csc(1)", "Trigonometry", {{"x", ArgumentKind::Angle}}},
        {"cot", "Cotangent", "The cosine over the sine of the angle x.",
         "cot(1)", "Trigonometry", {{"x", ArgumentKind::Angle}}},
        {"asin", "Inverse sine", "The angle in [−90°, 90°] whose sine is x.",
         "asin(0.5)", "Trigonometry", {{"x", ArgumentKind::Number}}},
        {"acos", "Inverse cosine", "The angle in [0°, 180°] whose cosine is x.",
         "acos(0.5)", "Trigonometry", {{"x", ArgumentKind::Number}}},
        {"atan", "Inverse tangent", "The angle in (−90°, 90°) whose tangent is x.",
         "atan(1)", "Trigonometry", {{"x", ArgumentKind::Number}}},
        {"asec", "Inverse secant", "The angle whose secant is x, the inverse cosine of 1/x.",
         "asec(2)", "Trigonometry", {{"x", ArgumentKind::Number}}},
        {"acsc", "Inverse cosecant", "The angle whose cosecant is x, the inverse sine of 1/x.",
         "acsc(2)", "Trigonometry", {{"x", ArgumentKind::Number}}},
        {"acot", "Inverse cotangent", "The angle whose cotangent is x: the inverse tangent of 1/x, and 90° at 0.",
         "acot(2)", "Trigonometry", {{"x", ArgumentKind::Number}}},
        {"atan2", "Angle of a point", "The angle in (−180°, 180°] of the point (x, y).",
         "atan2(1, -1)", "Trigonometry", {{"y", ArgumentKind::Number}, {"x", ArgumentKind::Number}}},
        {"sinc", "Cardinal sine", "sin(x)/x, and 1 at 0.",
         "sinc(1)", "Trigonometry", {{"x", ArgumentKind::Number}}},
        {"sinh", "Hyperbolic sine", "(eˣ − e⁻ˣ)/2.",
         "sinh(1)", "Hyperbolic", {{"x", ArgumentKind::Number}}},
        {"cosh", "Hyperbolic cosine", "(eˣ + e⁻ˣ)/2.",
         "cosh(1)", "Hyperbolic", {{"x", ArgumentKind::Number}}},
        {"tanh", "Hyperbolic tangent", "sinh(x)/cosh(x).",
         "tanh(0.5)", "Hyperbolic", {{"x", ArgumentKind::Number}}},
        {"sech", "Hyperbolic secant", "One over cosh(x).",
         "sech(1)", "Hyperbolic", {{"x", ArgumentKind::Number}}},
        {"csch", "Hyperbolic cosecant", "One over sinh(x).",
         "csch(1)", "Hyperbolic", {{"x", ArgumentKind::Number}}},
        {"coth", "Hyperbolic cotangent", "cosh(x)/sinh(x).",
         "coth(1)", "Hyperbolic", {{"x", ArgumentKind::Number}}},
        {"asinh", "Inverse hyperbolic sine", "The number whose hyperbolic sine is x.",
         "asinh(1)", "Hyperbolic", {{"x", ArgumentKind::Number}}},
        {"acosh", "Inverse hyperbolic cosine", "The non-negative number whose hyperbolic cosine is x.",
         "acosh(2)", "Hyperbolic", {{"x", ArgumentKind::Number}}},
        {"atanh", "Inverse hyperbolic tangent", "The number whose hyperbolic tangent is x.",
         "atanh(0.5)", "Hyperbolic", {{"x", ArgumentKind::Number}}},
        {"asech", "Inverse hyperbolic secant", "The non-negative number whose hyperbolic secant is x.",
         "asech(0.5)", "Hyperbolic", {{"x", ArgumentKind::Number}}},
        {"acsch", "Inverse hyperbolic cosecant", "The number whose hyperbolic cosecant is x.",
         "acsch(2)", "Hyperbolic", {{"x", ArgumentKind::Number}}},
        {"acoth", "Inverse hyperbolic cotangent", "The number whose hyperbolic cotangent is x.",
         "acoth(2)", "Hyperbolic", {{"x", ArgumentKind::Number}}},
        {"abs", "Absolute value", "x without its sign.",
         "abs(-3)", "Rounding and parts", {{"x", ArgumentKind::Number}}},
        {"sgn", "Sign", "−1, 0 or 1, as x is negative, zero or positive.",
         "sgn(-4)", "Rounding and parts", {{"x", ArgumentKind::Number}}},
        {"floor", "Round down", "The largest whole number not above x.",
         "floor(2.7)", "Rounding and parts", {{"x", ArgumentKind::Number}}},
        {"ceil", "Round up", "The smallest whole number not below x.",
         "ceil(2.2)", "Rounding and parts", {{"x", ArgumentKind::Number}}},
        {"round", "Round", "The nearest whole number; halves away from zero.",
         "round(2.5)", "Rounding and parts", {{"x", ArgumentKind::Number}}},
        {"trunc", "Integer part", "x without its fractional part, rounded toward zero.",
         "trunc(-2.7)", "Rounding and parts", {{"x", ArgumentKind::Number}}},
        {"frac", "Fractional part", "x minus its integer part.",
         "frac(2.75)", "Rounding and parts", {{"x", ArgumentKind::Number}}},
        {"clip", "Clip", "x, limited to the range from lo to hi.",
         "clip(5, 0, 2)", "Rounding and parts", {{"x", ArgumentKind::Number}, {"lo", ArgumentKind::Number}, {"hi", ArgumentKind::Number}}},
        {"numerator", "Numerator", "The numerator of x as a reduced fraction.",
         "numerator(0.75)", "Rounding and parts", {{"x", ArgumentKind::Number}}},
        {"denominator", "Denominator", "The denominator of x as a reduced fraction.",
         "denominator(0.75)", "Rounding and parts", {{"x", ArgumentKind::Number}}},
        {"mod", "Modulo", "The remainder of a divided by b, with the sign of a (or of b, when the setting says so).",
         "mod(7, 3)", "Integers", {{"a", ArgumentKind::Number}, {"b", ArgumentKind::Number}}},
        {"rem", "Remainder", "The remainder of a divided by b, with the sign of a.",
         "rem(-7, 3)", "Integers", {{"a", ArgumentKind::Number}, {"b", ArgumentKind::Number}}},
        {"floormod", "Floored remainder", "The remainder of a divided by b, with the sign of b.",
         "floormod(-7, 3)", "Integers", {{"a", ArgumentKind::Number}, {"b", ArgumentKind::Number}}},
        {"gcd", "Greatest common divisor", "The largest whole number dividing both a and b.",
         "gcd(12, 18)", "Integers", {{"a", ArgumentKind::Integer}, {"b", ArgumentKind::Integer}}},
        {"lcm", "Least common multiple", "The smallest positive whole number divisible by a and b.",
         "lcm(4, 6)", "Integers", {{"a", ArgumentKind::Integer}, {"b", ArgumentKind::Integer}}},
        {"nCr", "Combinations", "The ways to choose r of n things, order ignored.",
         "nCr(5, 2)", "Integers", {{"n", ArgumentKind::Integer}, {"r", ArgumentKind::Integer}}},
        {"nPr", "Permutations", "The ways to arrange r of n things in order.",
         "nPr(5, 2)", "Integers", {{"n", ArgumentKind::Integer}, {"r", ArgumentKind::Integer}}},
        {"mean", "Mean", "The sum of the values over their count.",
         "mean(1, 2, 3)", "Statistics", {{"value", ArgumentKind::Number}}},
        {"median", "Median", "The middle value, or the mean of the two middle ones.",
         "median(3, 1, 2)", "Statistics", {{"value", ArgumentKind::Number}}},
        {"var", "Sample variance", "The squared deviations from the mean over n − 1.",
         "var(2, 4, 4, 5)", "Statistics", {{"value", ArgumentKind::Number}}},
        {"stdev", "Sample standard deviation", "The square root of the sample variance.",
         "stdev(2, 4, 4, 5)", "Statistics", {{"value", ArgumentKind::Number}}},
        {"varp", "Population variance", "The squared deviations from the mean over n.",
         "varp(2, 4, 4, 5)", "Statistics", {{"value", ArgumentKind::Number}}},
        {"stdevp", "Population standard deviation", "The square root of the population variance.",
         "stdevp(2, 4, 4, 5)", "Statistics", {{"value", ArgumentKind::Number}}},
        {"sum", "Sum", "The term added up for each whole value of its variable from `from` to `to`.",
         "sum(x^2; 1; 10)", "Sums and products", {{"term", ArgumentKind::Number}, {"from", ArgumentKind::Integer}, {"to", ArgumentKind::Integer}, {"variable", ArgumentKind::Number}}},
        {"product", "Product", "The term multiplied for each whole value of its variable from `from` to `to`.",
         "product(x; 1; 5)", "Sums and products", {{"term", ArgumentKind::Number}, {"from", ArgumentKind::Integer}, {"to", ArgumentKind::Integer}, {"variable", ArgumentKind::Number}}},
        {"gamma", "Gamma function", "The factorial extended to real numbers: gamma(n) = (n − 1)!.",
         "gamma(0.5)", "Special functions", {{"x", ArgumentKind::Number}}},
        {"lgamma", "Log-gamma", "The natural logarithm of the absolute value of gamma(x).",
         "lgamma(100)", "Special functions", {{"x", ArgumentKind::Number}}},
        {"digamma", "Digamma", "The derivative of lgamma.",
         "digamma(1)", "Special functions", {{"x", ArgumentKind::Number}}},
        {"beta", "Beta function", "gamma(a)·gamma(b)/gamma(a + b).",
         "beta(2, 3)", "Special functions", {{"a", ArgumentKind::Number}, {"b", ArgumentKind::Number}}},
        {"erf", "Error function", "2/√π times the integral of e^(−t²) from 0 to x.",
         "erf(1)", "Special functions", {{"x", ArgumentKind::Number}}},
        {"erfc", "Complementary error function", "1 − erf(x), accurate even when tiny.",
         "erfc(2)", "Special functions", {{"x", ArgumentKind::Number}}},
        {"erfinv", "Inverse error function", "The x with erf(x) = y.",
         "erfinv(0.5)", "Special functions", {{"y", ArgumentKind::Number}}},
        {"erfcinv", "Inverse complementary error function", "The x with erfc(x) = z.",
         "erfcinv(0.01)", "Special functions", {{"z", ArgumentKind::Number}}},
        {"gammap", "Regularized lower incomplete gamma", "The integral of t^(a−1) e^(−t) from 0 to x, over gamma(a).",
         "gammap(2, 3)", "Probability", {{"a", ArgumentKind::Number}, {"x", ArgumentKind::Number}}},
        {"gammaq", "Regularized upper incomplete gamma", "1 − gammap(a, x), accurate even when tiny.",
         "gammaq(2, 3)", "Probability", {{"a", ArgumentKind::Number}, {"x", ArgumentKind::Number}}},
        {"igamma", "Upper incomplete gamma", "The integral of t^(a−1) e^(−t) from x to infinity.",
         "igamma(2, 3)", "Probability", {{"a", ArgumentKind::Number}, {"x", ArgumentKind::Number}}},
        {"gammainc", "Lower incomplete gamma", "The integral of t^(a−1) e^(−t) from 0 to x.",
         "gammainc(2, 3)", "Probability", {{"a", ArgumentKind::Number}, {"x", ArgumentKind::Number}}},
        {"betainc", "Regularized incomplete beta", "The integral of t^(a−1)(1 − t)^(b−1) from 0 to x, over beta(a, b).",
         "betainc(2, 5, 0.3)", "Probability", {{"a", ArgumentKind::Number}, {"b", ArgumentKind::Number}, {"x", ArgumentKind::Number}}},
        {"betaincinv", "Inverse incomplete beta", "The x with betainc(a, b, x) = y.",
         "betaincinv(2, 5, 0.5)", "Probability", {{"a", ArgumentKind::Number}, {"b", ArgumentKind::Number}, {"y", ArgumentKind::Number}}},
        {"uncertainty", "Value with uncertainty", "x, whose true value lies within u of it.",
         "uncertainty(5, 0.2)", "Uncertainty", {{"x", ArgumentKind::Number}, {"u", ArgumentKind::Number}}},
        {"errorPart", "Error part", "The worst-case uncertainty x carries from its uncertain inputs, as a number.",
         "errorPart(5±0.2)", "Uncertainty", {{"x", ArgumentKind::Number}}},
    };
    return rows;
}

}  // namespace

const FunctionText* functionText(std::string_view name) {
    for (const FunctionText& row : table())
        if (row.name == name) return &row;
    return nullptr;
}

std::vector<std::string> categories() {
    return {"Constants", "Powers and roots", "Logarithms", "Trigonometry", "Hyperbolic", "Rounding and parts",
            "Integers", "Statistics", "Sums and products", "Special functions", "Probability", "Uncertainty"};
}

}  // namespace calculate_core::detail
