#pragma once

// Generated by tools/physical_constants.py from tools/codata-2022.txt (CODATA 2022, published by
// NIST) and tools/physical-constants.tsv; do not edit.

#include <array>
#include <string_view>

namespace calculate_core::detail {

struct PhysicalConstant {
    std::string_view name;        // as typed: "G"
    std::string_view quantity;    // CODATA's name: "Newtonian constant of gravitation"
    std::string_view definition;  // what the name stands for: "6.67430e-11+/-0.00015e-11", "h/(2*pi)"
    std::string_view nistValue;   // the value as NIST prints it, spaces removed: "1.054571817...e-34"
    std::string_view unit;        // SI, as NIST writes it: "m^3 kg^-1 s^-2"; empty for pure numbers
    std::array<signed char, 7> dimension;  // exponents of m, kg, s, A, K, mol, cd; zeros when not coherent
    bool coherent;                // its unit is SI (MeV, u, eV… are not: no dimension then)
    bool exact;                   // exact by the definition of the SI
    std::string_view group;       // for lists: "Universal", "Electromagnetic", "Particle masses"…
};

inline constexpr std::array<PhysicalConstant, 89> physicalConstants{{
    {"c", "speed of light in vacuum", "299792458", "299792458", "m s^-1", {1, 0, -1, 0, 0, 0, 0}, true, true, "Universal"},
    {"h", "Planck constant", "6.62607015e-34", "6.62607015e-34", "J Hz^-1", {2, 1, -1, 0, 0, 0, 0}, true, true, "Universal"},
    {"hbar", "reduced Planck constant", "h/(2*pi)", "1.054571817...e-34", "J s", {2, 1, -1, 0, 0, 0, 0}, true, true, "Universal"},
    {"q_e", "elementary charge", "1.602176634e-19", "1.602176634e-19", "C", {0, 0, 1, 1, 0, 0, 0}, true, true, "Electromagnetic"},
    {"k_B", "Boltzmann constant", "1.380649e-23", "1.380649e-23", "J K^-1", {2, 1, -2, 0, -1, 0, 0}, true, true, "Physico-chemical"},
    {"N_A", "Avogadro constant", "6.02214076e23", "6.02214076e23", "mol^-1", {0, 0, 0, 0, 0, -1, 0}, true, true, "Physico-chemical"},
    {"dnu_Cs", "hyperfine transition frequency of Cs-133", "9192631770", "9192631770", "Hz", {0, 0, -1, 0, 0, 0, 0}, true, true, "Universal"},
    {"K_cd", "luminous efficacy", "683", "683", "lm W^-1", {-2, -1, 3, 0, 0, 0, 1}, true, true, "Universal"},
    {"G", "Newtonian constant of gravitation", "6.67430e-11+/-0.00015e-11", "6.67430e-11", "m^3 kg^-1 s^-2", {3, -1, -2, 0, 0, 0, 0}, true, false, "Universal"},
    {"g_n", "standard acceleration of gravity", "9.80665", "9.80665", "m s^-2", {1, 0, -2, 0, 0, 0, 0}, true, true, "Physico-chemical"},
    {"atm", "standard atmosphere", "101325", "101325", "Pa", {-1, 1, -2, 0, 0, 0, 0}, true, true, "Physico-chemical"},
    {"p_std", "standard-state pressure", "100000", "100000", "Pa", {-1, 1, -2, 0, 0, 0, 0}, true, true, "Physico-chemical"},
    {"R", "molar gas constant", "N_A*k_B", "8.314462618...", "J mol^-1 K^-1", {2, 1, -2, 0, -1, -1, 0}, true, true, "Physico-chemical"},
    {"F", "Faraday constant", "N_A*q_e", "96485.33212...", "C mol^-1", {0, 0, 1, 1, 0, -1, 0}, true, true, "Physico-chemical"},
    {"sigma_SB", "Stefan-Boltzmann constant", "2*pi^5*k_B^4/(15*h^3*c^2)", "5.670374419...e-8", "W m^-2 K^-4", {0, 1, -3, 0, -4, 0, 0}, true, true, "Physico-chemical"},
    {"c_1", "first radiation constant", "2*pi*h*c^2", "3.741771852...e-16", "W m^2", {4, 1, -3, 0, 0, 0, 0}, true, true, "Physico-chemical"},
    {"c_1L", "first radiation constant for spectral radiance", "2*h*c^2", "1.191042972...e-16", "W m^2 sr^-1", {4, 1, -3, 0, 0, 0, 0}, true, true, "Physico-chemical"},
    {"c_2", "second radiation constant", "h*c/k_B", "1.438776877...e-2", "m K", {1, 0, 0, 0, 1, 0, 0}, true, true, "Physico-chemical"},
    {"V_m", "molar volume of ideal gas (273.15 K, 100 kPa)", "N_A*k_B*273.15/100000", "22.71095464...e-3", "m^3 mol^-1", {3, 0, 0, 0, 0, -1, 0}, true, true, "Physico-chemical"},
    {"V_m_atm", "molar volume of ideal gas (273.15 K, 101.325 kPa)", "N_A*k_B*273.15/101325", "22.41396954...e-3", "m^3 mol^-1", {3, 0, 0, 0, 0, -1, 0}, true, true, "Physico-chemical"},
    {"n_0", "Loschmidt constant (273.15 K, 100 kPa)", "100000/(k_B*273.15)", "2.651645804...e25", "m^-3", {-3, 0, 0, 0, 0, 0, 0}, true, true, "Physico-chemical"},
    {"n_0_atm", "Loschmidt constant (273.15 K, 101.325 kPa)", "101325/(k_B*273.15)", "2.686780111...e25", "m^-3", {-3, 0, 0, 0, 0, 0, 0}, true, true, "Physico-chemical"},
    {"M_u", "molar mass constant", "1.00000000105e-3+/-0.00000000031e-3", "1.00000000105e-3", "kg mol^-1", {0, 1, 0, 0, 0, -1, 0}, true, false, "Physico-chemical"},
    {"mu_0", "vacuum mag. permeability", "1.25663706127e-6+/-0.00000000020e-6", "1.25663706127e-6", "N A^-2", {1, 1, -2, -2, 0, 0, 0}, true, false, "Electromagnetic"},
    {"eps_0", "vacuum electric permittivity", "8.8541878188e-12+/-0.0000000014e-12", "8.8541878188e-12", "F m^-1", {-3, -1, 4, 2, 0, 0, 0}, true, false, "Electromagnetic"},
    {"Z_0", "characteristic impedance of vacuum", "376.730313412+/-0.000000059", "376.730313412", "ohm", {2, 1, -3, -2, 0, 0, 0}, true, false, "Electromagnetic"},
    {"alpha", "fine-structure constant", "7.2973525643e-3+/-0.0000000011e-3", "7.2973525643e-3", "", {0, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"alpha_inv", "inverse fine-structure constant", "137.035999177+/-0.000000021", "137.035999177", "", {0, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"R_inf", "Rydberg constant", "10973731.568157+/-0.000012", "10973731.568157", "m^-1", {-1, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"a_0", "Bohr radius", "5.29177210544e-11+/-0.00000000082e-11", "5.29177210544e-11", "m", {1, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"E_h", "Hartree energy", "4.3597447222060e-18+/-0.0000000000048e-18", "4.3597447222060e-18", "J", {2, 1, -2, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"r_e", "classical electron radius", "2.8179403205e-15+/-0.0000000013e-15", "2.8179403205e-15", "m", {1, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"sigma_e", "Thomson cross section", "6.6524587051e-29+/-0.0000000062e-29", "6.6524587051e-29", "m^2", {2, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"lambda_C", "Compton wavelength", "2.42631023538e-12+/-0.00000000076e-12", "2.42631023538e-12", "m", {1, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"lambdabar_C", "reduced Compton wavelength", "3.8615926744e-13+/-0.0000000012e-13", "3.8615926744e-13", "m", {1, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"mu_B", "Bohr magneton", "9.2740100657e-24+/-0.0000000029e-24", "9.2740100657e-24", "J T^-1", {2, 0, 0, 1, 0, 0, 0}, true, false, "Electromagnetic"},
    {"mu_N", "nuclear magneton", "5.0507837393e-27+/-0.0000000016e-27", "5.0507837393e-27", "J T^-1", {2, 0, 0, 1, 0, 0, 0}, true, false, "Electromagnetic"},
    {"Phi_0", "mag. flux quantum", "h/(2*q_e)", "2.067833848...e-15", "Wb", {2, 1, -2, -1, 0, 0, 0}, true, true, "Electromagnetic"},
    {"G_0", "conductance quantum", "2*q_e^2/h", "7.748091729...e-5", "S", {-2, -1, 3, 2, 0, 0, 0}, true, true, "Electromagnetic"},
    {"K_J", "Josephson constant", "2*q_e/h", "483597.8484...e9", "Hz V^-1", {-2, -1, 2, 1, 0, 0, 0}, true, true, "Electromagnetic"},
    {"R_K", "von Klitzing constant", "h/q_e^2", "25812.80745...", "ohm", {2, 1, -3, -2, 0, 0, 0}, true, true, "Electromagnetic"},
    {"eV", "electron volt", "1.602176634e-19", "1.602176634e-19", "J", {2, 1, -2, 0, 0, 0, 0}, true, true, "Physico-chemical"},
    {"m_u", "atomic mass constant", "1.66053906892e-27+/-0.00000000052e-27", "1.66053906892e-27", "kg", {0, 1, 0, 0, 0, 0, 0}, true, false, "Physico-chemical"},
    {"m_e", "electron mass", "9.1093837139e-31+/-0.0000000028e-31", "9.1093837139e-31", "kg", {0, 1, 0, 0, 0, 0, 0}, true, false, "Particle masses"},
    {"m_p", "proton mass", "1.67262192595e-27+/-0.00000000052e-27", "1.67262192595e-27", "kg", {0, 1, 0, 0, 0, 0, 0}, true, false, "Particle masses"},
    {"m_n", "neutron mass", "1.67492750056e-27+/-0.00000000085e-27", "1.67492750056e-27", "kg", {0, 1, 0, 0, 0, 0, 0}, true, false, "Particle masses"},
    {"m_d", "deuteron mass", "3.3435837768e-27+/-0.0000000010e-27", "3.3435837768e-27", "kg", {0, 1, 0, 0, 0, 0, 0}, true, false, "Particle masses"},
    {"m_h", "helion mass", "5.0064127862e-27+/-0.0000000016e-27", "5.0064127862e-27", "kg", {0, 1, 0, 0, 0, 0, 0}, true, false, "Particle masses"},
    {"m_t", "triton mass", "5.0073567512e-27+/-0.0000000016e-27", "5.0073567512e-27", "kg", {0, 1, 0, 0, 0, 0, 0}, true, false, "Particle masses"},
    {"m_alpha", "alpha particle mass", "6.6446573450e-27+/-0.0000000021e-27", "6.6446573450e-27", "kg", {0, 1, 0, 0, 0, 0, 0}, true, false, "Particle masses"},
    {"m_mu", "muon mass", "1.883531627e-28+/-0.000000042e-28", "1.883531627e-28", "kg", {0, 1, 0, 0, 0, 0, 0}, true, false, "Particle masses"},
    {"m_tau", "tau mass", "3.16754e-27+/-0.00021e-27", "3.16754e-27", "kg", {0, 1, 0, 0, 0, 0, 0}, true, false, "Particle masses"},
    {"m_e_u", "electron mass in u", "5.485799090441e-4+/-0.000000000097e-4", "5.485799090441e-4", "u", {0, 0, 0, 0, 0, 0, 0}, false, false, "Particle masses"},
    {"m_p_u", "proton mass in u", "1.0072764665789+/-0.0000000000083", "1.0072764665789", "u", {0, 0, 0, 0, 0, 0, 0}, false, false, "Particle masses"},
    {"m_n_u", "neutron mass in u", "1.00866491606+/-0.00000000040", "1.00866491606", "u", {0, 0, 0, 0, 0, 0, 0}, false, false, "Particle masses"},
    {"m_e_MeV", "electron mass energy equivalent in MeV", "0.51099895069+/-0.00000000016", "0.51099895069", "MeV", {0, 0, 0, 0, 0, 0, 0}, false, false, "Particle masses"},
    {"m_p_MeV", "proton mass energy equivalent in MeV", "938.27208943+/-0.00000029", "938.27208943", "MeV", {0, 0, 0, 0, 0, 0, 0}, false, false, "Particle masses"},
    {"m_n_MeV", "neutron mass energy equivalent in MeV", "939.56542194+/-0.00000048", "939.56542194", "MeV", {0, 0, 0, 0, 0, 0, 0}, false, false, "Particle masses"},
    {"m_mu_MeV", "muon mass energy equivalent in MeV", "105.6583755+/-0.0000023", "105.6583755", "MeV", {0, 0, 0, 0, 0, 0, 0}, false, false, "Particle masses"},
    {"m_p_m_e", "proton-electron mass ratio", "1836.152673426+/-0.000000032", "1836.152673426", "", {0, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"m_mu_m_e", "muon-electron mass ratio", "206.7682827+/-0.0000046", "206.7682827", "", {0, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"mu_e", "electron mag. mom.", "-9.2847646917e-24+/-0.0000000029e-24", "-9.2847646917e-24", "J T^-1", {2, 0, 0, 1, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"mu_p", "proton mag. mom.", "1.41060679545e-26+/-0.00000000060e-26", "1.41060679545e-26", "J T^-1", {2, 0, 0, 1, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"mu_n", "neutron mag. mom.", "-9.6623653e-27+/-0.0000023e-27", "-9.6623653e-27", "J T^-1", {2, 0, 0, 1, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"mu_mu", "muon mag. mom.", "-4.49044830e-26+/-0.00000010e-26", "-4.49044830e-26", "J T^-1", {2, 0, 0, 1, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"g_e", "electron g factor", "-2.00231930436092+/-0.00000000000036", "-2.00231930436092", "", {0, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"g_p", "proton g factor", "5.5856946893+/-0.0000000016", "5.5856946893", "", {0, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"g_mu", "muon g factor", "-2.00233184123+/-0.00000000082", "-2.00233184123", "", {0, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"a_e", "electron mag. mom. anomaly", "1.15965218046e-3+/-0.00000000018e-3", "1.15965218046e-3", "", {0, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"a_mu", "muon mag. mom. anomaly", "1.16592062e-3+/-0.00000041e-3", "1.16592062e-3", "", {0, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"gamma_e", "electron gyromag. ratio", "1.76085962784e11+/-0.00000000055e11", "1.76085962784e11", "s^-1 T^-1", {0, -1, 1, 1, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"gamma_p", "proton gyromag. ratio", "2.6752218708e8+/-0.0000000011e8", "2.6752218708e8", "s^-1 T^-1", {0, -1, 1, 1, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"r_p", "proton rms charge radius", "8.4075e-16+/-0.0064e-16", "8.4075e-16", "m", {1, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"r_d", "deuteron rms charge radius", "2.12778e-15+/-0.00027e-15", "2.12778e-15", "m", {1, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"e_m_e", "electron charge to mass quotient", "-1.75882000838e11+/-0.00000000055e11", "-1.75882000838e11", "C kg^-1", {0, -1, 1, 1, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"k_B_eV", "Boltzmann constant in eV/K", "k_B/q_e", "8.617333262...e-5", "eV K^-1", {0, 0, 0, 0, 0, 0, 0}, false, true, "Physico-chemical"},
    {"h_eV", "Planck constant in eV/Hz", "h/q_e", "4.135667696...e-15", "eV Hz^-1", {0, 0, 0, 0, 0, 0, 0}, false, true, "Physico-chemical"},
    {"hbar_eV", "reduced Planck constant in eV s", "h/(2*pi*q_e)", "6.582119569...e-16", "eV s", {0, 0, 0, 0, 0, 0, 0}, false, true, "Physico-chemical"},
    {"hbarc", "reduced Planck constant times c in MeV fm", "h*c/(2*pi*q_e)*1e9", "197.3269804...", "MeV fm", {0, 0, 0, 0, 0, 0, 0}, false, true, "Atomic and nuclear"},
    {"Ry_eV", "Rydberg constant times hc in eV", "13.605693122990+/-0.000000000015", "13.605693122990", "eV", {0, 0, 0, 0, 0, 0, 0}, false, false, "Atomic and nuclear"},
    {"E_h_eV", "Hartree energy in eV", "27.211386245981+/-0.000000000030", "27.211386245981", "eV", {0, 0, 0, 0, 0, 0, 0}, false, false, "Atomic and nuclear"},
    {"N_A_h", "molar Planck constant", "N_A*h", "3.990312712...e-10", "J Hz^-1 mol^-1", {2, 1, -1, 0, 0, -1, 0}, true, true, "Physico-chemical"},
    {"G_F", "Fermi coupling constant", "1.1663787e-5+/-0.0000006e-5", "1.1663787e-5", "GeV^-2", {0, 0, 0, 0, 0, 0, 0}, false, false, "Atomic and nuclear"},
    {"sin2_theta_W", "weak mixing angle", "0.22305+/-0.00023", "0.22305", "", {0, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"m_W_m_Z", "W to Z mass ratio", "0.88145+/-0.00013", "0.88145", "", {0, 0, 0, 0, 0, 0, 0}, true, false, "Atomic and nuclear"},
    {"l_P", "Planck length", "1.616255e-35+/-0.000018e-35", "1.616255e-35", "m", {1, 0, 0, 0, 0, 0, 0}, true, false, "Planck units"},
    {"m_P", "Planck mass", "2.176434e-8+/-0.000024e-8", "2.176434e-8", "kg", {0, 1, 0, 0, 0, 0, 0}, true, false, "Planck units"},
    {"t_P", "Planck time", "5.391247e-44+/-0.000060e-44", "5.391247e-44", "s", {0, 0, 1, 0, 0, 0, 0}, true, false, "Planck units"},
    {"T_P", "Planck temperature", "1.416784e32+/-0.000016e32", "1.416784e32", "K", {0, 0, 0, 0, 1, 0, 0}, true, false, "Planck units"},
}};

}  // namespace calculate_core::detail
